export const ignorePatterns = [
  '**/.source/**',
  '**/.next/**',
  '**/.turbo/**',
  '**/.vercel/**',
  '**/.claude/**',
  '**/dist/**',
  '**/build/**',
  '**/coverage/**',
  '**/out/**',
  '**/node_modules/**',
  '.agents/**',
  '**/next-env.d.ts',
  '**/*.gen.ts',
  '**/*.generated.ts',
  'examples/svelte/src/lib/index.ts',
  'pnpm-lock.yaml',
]
